ERROR:common.utils:Traceback (most recent call last):
  File "/home/kevindsouza/Documents/projects/latentGenome/src/common/utils.py", line 18, in load_config_as_class
    with open(config_path, 'r') as infile:
FileNotFoundError: [Errno 2] No such file or directory: '/data2/latent/data/avocado/avocado-config.yaml'

